"use client";

import React, { useState, useMemo } from "react";
import Image from "next/image";
import Link from "next/link";
import { Search, Trophy, Medal, Award, Sparkles, GraduationCap, ArrowRight, UserCheck, Calendar } from "lucide-react";
import { cn } from "@/lib/utils";
import { Container } from "@/components/layout/container";
import { Button } from "@/components/ui/button";

import type { Topper } from "@/lib/content/types";

interface SelectionsClientProps {
  locale: "hi" | "en";
  initialSelections?: Topper[];
}

// Sample authentic selections list
const TOPPERS_DATA: Topper[] = [
  {
    id: "1",
    name: "अजीत कुमार मिश्रा",
    nameEn: "Ajeet Kumar Mishra",
    rank: 1,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    quote: "आकार IAS के टेस्ट डिस्कशन और पर्सनल गाइडेंस ने मेरी उत्तर लेखन शैली में क्रांतिकारी सुधार किया जिससे मुझे प्रथम रैंक प्राप्त हुई।",
    quoteEn: "Aakar IAS's test discussion and personal guidance revolutionized my answer writing style, helping me secure Rank 1.",
    rollNo: "MP30248",
    isRanker: true,
  },
  {
    id: "2",
    name: "विवेक अग्रवाल",
    nameEn: "Vivek Agrawal",
    rank: 1,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    quote: "फैकल्टी का निरंतर समर्थन और सटीक स्टडी मटेरियल मेरी सफलता की मजबूत नींव बने और मैंने प्रथम स्थान प्राप्त किया।",
    quoteEn: "Constant support from faculty and precise study material formed a strong foundation for my success and securing Rank 1.",
    rollNo: "MP30891",
    isRanker: true,
  },
  {
    id: "3",
    name: "अदिति तोमर",
    nameEn: "Aditi Tomar",
    rank: 1,
    exam: "MPPSC",
    year: 2022,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    rollNo: "MP20248",
    isRanker: false,
  },
  {
    id: "4",
    name: "शुभम यादव",
    nameEn: "Shubham Yadav",
    rank: 2,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    rollNo: "MP30892",
    isRanker: false,
  },
  {
    id: "5",
    name: "प्रिया शर्मा",
    nameEn: "Priya Sharma",
    rank: 5,
    exam: "UPSC",
    year: 2024,
    post: "आईएएस (IAS)",
    postEn: "IAS",
    avatar: "",
    rollNo: "0894562",
    isRanker: false,
  },
  {
    id: "6",
    name: "अमित द्विवेदी",
    nameEn: "Amit Dwivedi",
    rank: 8,
    exam: "MPPSC",
    year: 2022,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    rollNo: "MP20412",
    isRanker: false,
  },
  {
    id: "7",
    name: "निहारिका जैन",
    nameEn: "Niharika Jain",
    rank: 12,
    exam: "UPSC",
    year: 2024,
    post: "आईपीएस (IPS)",
    postEn: "IPS",
    avatar: "",
    rollNo: "0587421",
    isRanker: false,
  },
  {
    id: "8",
    name: "विकास चौधरी",
    nameEn: "Vikas Choudhary",
    rank: 15,
    exam: "MPPSC",
    year: 2023,
    post: "वाणिज्यिक कर अधिकारी (CTO)",
    postEn: "Commercial Tax Officer",
    avatar: "",
    rollNo: "MP30560",
    isRanker: false,
  },
  {
    id: "9",
    name: "श्वेता सिंह",
    nameEn: "Shweta Singh",
    rank: 21,
    exam: "UPSC",
    year: 2023,
    post: "आईएफएस (IFS)",
    postEn: "IFS",
    avatar: "",
    rollNo: "0145892",
    isRanker: false,
  },
  {
    id: "10",
    name: "रोहित राठौर",
    nameEn: "Rohit Rathore",
    rank: 24,
    exam: "MPPSC",
    year: 2022,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    rollNo: "MP20120",
    isRanker: false,
  },
  {
    id: "11",
    name: "आदित्य मिश्रा",
    nameEn: "Aditya Mishra",
    rank: 35,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक निदेशक (Assistant Director)",
    postEn: "Assistant Director",
    avatar: "",
    rollNo: "MP30742",
    isRanker: false,
  },
  {
    id: "12",
    name: "अंजलि गुप्ता",
    nameEn: "Anjali Gupta",
    rank: 42,
    exam: "UPSC",
    year: 2022,
    post: "आईआरएस (IRS)",
    postEn: "IRS",
    avatar: "",
    rollNo: "0325419",
    isRanker: false,
  },
  {
    id: "13",
    name: "गौरव राजपूत",
    nameEn: "Gaurav Rajput",
    rank: 48,
    exam: "MPPSC",
    year: 2023,
    post: "जेल अधीक्षक (Jail Superintendent)",
    postEn: "Jail Superintendent",
    avatar: "",
    rollNo: "MP31190",
    isRanker: false,
  },
  {
    id: "14",
    name: "मोनिका पटेल",
    nameEn: "Monica Patel",
    rank: 56,
    exam: "MPPSC",
    year: 2024,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    rollNo: "MP40112",
    isRanker: false,
  },
  {
    id: "15",
    name: "नृपेंद्र सिंह",
    nameEn: "Nripendra Singh",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "16",
    name: "अदिति जैन",
    nameEn: "Aditi Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "17",
    name: "सिद्धार्थ मेहता",
    nameEn: "Siddharth Mehta",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "18",
    name: "गोविंद सिंह लोधी",
    nameEn: "Govind Singh Lodhi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "19",
    name: "स्वाति सिंह बघेल",
    nameEn: "Swati Singh Baghel",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "20",
    name: "शैलेश मिश्रा",
    nameEn: "Shailesh Mishra",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "21",
    name: "विवेक सिंह दांगी",
    nameEn: "Vivek Singh Dangi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "22",
    name: "मयंका चौधरिया",
    nameEn: "Mayanka Chaudhariya",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "23",
    name: "जितेन्द्र कुमार",
    nameEn: "Jitendra Kumar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "24",
    name: "अमित जैन",
    nameEn: "Amit Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "जनपद पंचायत सीईओ (Janpad Panchayat CEO)",
    postEn: "Janpad Panchayat CEO",
    avatar: "",
    isRanker: false,
  },
  {
    id: "25",
    name: "अंकित सिंघई",
    nameEn: "Ankit Singhai",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "जनपद पंचायत सीईओ (Janpad Panchayat CEO)",
    postEn: "Janpad Panchayat CEO",
    avatar: "",
    isRanker: false,
  },
  {
    id: "26",
    name: "लोकेश साहू",
    nameEn: "Lokesh Sahu",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "जनपद पंचायत सीईओ (Janpad Panchayat CEO)",
    postEn: "Janpad Panchayat CEO",
    avatar: "",
    isRanker: false,
  },
  {
    id: "27",
    name: "आकाश जैन",
    nameEn: "Akash Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "जनपद पंचायत सीईओ (Janpad Panchayat CEO)",
    postEn: "Janpad Panchayat CEO",
    avatar: "",
    isRanker: false,
  },
  {
    id: "28",
    name: "निलेश मोर्य",
    nameEn: "Nilesh Morya",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "जनपद पंचायत सीईओ (Janpad Panchayat CEO)",
    postEn: "Janpad Panchayat CEO",
    avatar: "",
    isRanker: false,
  },
  {
    id: "29",
    name: "निलेश वर्मन",
    nameEn: "Nilesh Varman",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "जनपद पंचायत सीईओ (Janpad Panchayat CEO)",
    postEn: "Janpad Panchayat CEO",
    avatar: "",
    isRanker: false,
  },
  {
    id: "30",
    name: "भारती ठाकुर",
    nameEn: "Bharti Thakur",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "ब्लॉक विकास अधिकारी (BDO)",
    postEn: "Block Development Officer (BDO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "31",
    name: "ऋतिक लोधंकी",
    nameEn: "Hritik Lodhanki",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "ब्लॉक विकास अधिकारी (BDO)",
    postEn: "Block Development Officer (BDO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "32",
    name: "अजय वर्मा",
    nameEn: "Ajay Verma",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "33",
    name: "कल्पना प्रजापति",
    nameEn: "Kalpana Prajapati",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "34",
    name: "चंदन शाह",
    nameEn: "Chandan Shah",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी उपनिरीक्षक (Excise Sub Inspector)",
    postEn: "Excise Sub Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "35",
    name: "कुणभांकांत पटेल",
    nameEn: "Kunbhakant Patel",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "36",
    name: "आशीष पांडे",
    nameEn: "Ashish Pandey",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "37",
    name: "आदित्य धुल्ला",
    nameEn: "Aditya Dhulla",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "38",
    name: "विष्णु गुर्जर",
    nameEn: "Vishnu Gurjar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "39",
    name: "उत्तम कलमोदिया",
    nameEn: "Uttam Kalmodiya",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "40",
    name: "पंकज जैन",
    nameEn: "Pankaj Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "41",
    name: "एकता आसवानी",
    nameEn: "Ekta Aswani",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "42",
    name: "गौरव जोशी",
    nameEn: "Gaurav Joshi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "43",
    name: "शुभम राय",
    nameEn: "Shubham Rai",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "44",
    name: "सलोनी जैन",
    nameEn: "Saloni Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "45",
    name: "राहुल पोर्तवाल",
    nameEn: "Rahul Portwal",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "46",
    name: "श्रवण यादव",
    nameEn: "Shravan Yadav",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "47",
    name: "विनीत कुमार दीक्षित",
    nameEn: "Vineet Kumar Dixit",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "48",
    name: "देवराज राजपूत",
    nameEn: "Devraj Rajput",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "49",
    name: "मनोज पाल",
    nameEn: "Manoj Pal",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "50",
    name: "दुर्गेश कुमार",
    nameEn: "Durgesh Kumar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "51",
    name: "वंदना गुर्जर",
    nameEn: "Vandana Gurjar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "52",
    name: "यशस्वी मीणा",
    nameEn: "Yashaswi Meena",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "53",
    name: "श्रुति सिंहई",
    nameEn: "Shruti Singhai",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "54",
    name: "अनामिका जैन",
    nameEn: "Anamika Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "55",
    name: "ऋषिका यादव",
    nameEn: "Rishika Yadav",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "56",
    name: "हालिनी त्रिपाठी",
    nameEn: "Halini Tripathi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "57",
    name: "शुभी यादव",
    nameEn: "Shubhi Yadav",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "58",
    name: "कृतिका मालवीय",
    nameEn: "Kritika Malviya",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "59",
    name: "भानु गुर्जर प्रजापति",
    nameEn: "Bhanu Gurjar Prajapati",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "60",
    name: "दीपक वर्मा",
    nameEn: "Deepak Verma",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "61",
    name: "नीलम गाडगे",
    nameEn: "Neelam Gadge",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "62",
    name: "प्रखर जैन",
    nameEn: "Prakhar Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "63",
    name: "कल्याणी पराशरी",
    nameEn: "Kalyani Parashari",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "64",
    name: "दीपा गौंड",
    nameEn: "Deepa Gound",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "65",
    name: "प्रदीप सिंह यादव",
    nameEn: "Pradeep Singh Yadav",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "66",
    name: "जितेंद्र बघेल",
    nameEn: "Jitendra Baghel",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "67",
    name: "जूवेंद्र बघेल",
    nameEn: "Juvendra Baghel",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "68",
    name: "विशाल भलके",
    nameEn: "Vishal Bhalke",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "69",
    name: "अनुराग ठाकुर",
    nameEn: "Anurag Thakur",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "70",
    name: "योगेश शर्मा",
    nameEn: "Yogesh Sharma",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "71",
    name: "नीलम पचिका",
    nameEn: "Neelam Pachika",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "72",
    name: "सिद्धांत जैन",
    nameEn: "Siddhant Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "73",
    name: "प्रियं अग्रवाल",
    nameEn: "Priyam Agrawal",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "74",
    name: "मोहित धुल्ला",
    nameEn: "Mohit Dhulla",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "75",
    name: "रामेंद्र धुल्ला",
    nameEn: "Ramendra Dhulla",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "76",
    name: "शिवांगी पांडे",
    nameEn: "Shivangi Pandey",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "77",
    name: "रोशनी पवार",
    nameEn: "Roshni Pawar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "78",
    name: "दिव्यानी जाधव",
    nameEn: "Divyani Jadhav",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "79",
    name: "श्रद्धा मेरावी",
    nameEn: "Shraddha Meravi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "81",
    name: "ऋषभ अवस्थी",
    nameEn: "Rishabh Awasthi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "82",
    name: "शिवानी",
    nameEn: "Shivani",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "83",
    name: "हरिता देवे",
    nameEn: "Harita Deve",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "84",
    name: "रुचि जाट",
    nameEn: "Ruchi Jat",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "85",
    name: "स्वर्णा दीवान",
    nameEn: "Swarna Diwan",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "86",
    name: "सुमेध कुमार द्विवेदी",
    nameEn: "Sumedh Kumar Dwivedi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "87",
    name: "मनीष धनगर",
    nameEn: "Manish Dhangar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "88",
    name: "ज्योति लिल्हारे",
    nameEn: "Jyoti Lilhare",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "89",
    name: "सोनाली राजपूत",
    nameEn: "Sonali Rajput",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "90",
    name: "अर्चना मिश्रा",
    nameEn: "Archana Mishra",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "91",
    name: "पूर्वा मंडलोई",
    nameEn: "Purva Mandloi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "92",
    name: "आलोक मार्को",
    nameEn: "Alok Marko",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "93",
    name: "सौरभ मिश्रा",
    nameEn: "Saurabh Mishra",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "94",
    name: "आयुषोष म. ठाकुर",
    nameEn: "Ayushosh M. Thakur",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "95",
    name: "निधि भारद्वाज",
    nameEn: "Nidhi Bhardwaj",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "96",
    name: "नेहा गंगोरे",
    nameEn: "Neha Gangore",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "97",
    name: "प्रशांत उडके",
    nameEn: "Prashant Udke",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "98",
    name: "प्रियंका भलावी",
    nameEn: "Priyanka Bhalavi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डिप्टी कलेक्टर (Deputy Collector)",
    postEn: "Deputy Collector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "99",
    name: "विवेक कुमार पटेल",
    nameEn: "Vivek Kumar Patel",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "100",
    name: "मोना मिश्रा",
    nameEn: "Mona Mishra",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "101",
    name: "पूजा तिवारी",
    nameEn: "Pooja Tiwari",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "102",
    name: "आरती करवेती",
    nameEn: "Aarti Karveti",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "103",
    name: "जयंत परस्ते",
    nameEn: "Jayant Paraste",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "104",
    name: "प्रियांशु",
    nameEn: "Priyanshu",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "105",
    name: "दीपक सिंह मरावी",
    nameEn: "Deepak Singh Maravi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "106",
    name: "अक्षय डिंगरसे",
    nameEn: "Akshay Dingarse",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "107",
    name: "गगन हनवत",
    nameEn: "Gagan Hanwat",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "108",
    name: "रोशनी कुर्मी",
    nameEn: "Roshni Kurmi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "109",
    name: "अमित बाड़िया",
    nameEn: "Amit Badiya",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "110",
    name: "मासूम पाटले",
    nameEn: "Masoom Patle",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "111",
    name: "ललित बैरागी",
    nameEn: "Lalit Bairagi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "112",
    name: "आनंद कुमार राय",
    nameEn: "Anand Kumar Rai",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "डीएसपी (DSP)",
    postEn: "DSP",
    avatar: "",
    isRanker: false,
  },
  {
    id: "113",
    name: "उज्ज्वल यादव",
    nameEn: "Ujjwal Yadav",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "कनिष्ठ लेखापाल कार्यालय अधिकारी",
    postEn: "Junior Accountant Office Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "114",
    name: "रितु शर्मा",
    nameEn: "Ritu Sharma",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "वाणिज्यिक कर अधिकारी (CTO)",
    postEn: "Commercial Tax Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "115",
    name: "अंकिता त्रिवेदी",
    nameEn: "Ankita Trivedi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "वाणिज्यिक कर अधिकारी (CTO)",
    postEn: "Commercial Tax Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "116",
    name: "तेजस्विनी मारकोने",
    nameEn: "Tejaswini Markone",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "वाणिज्यिक कर अधिकारी (CTO)",
    postEn: "Commercial Tax Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "117",
    name: "जितेन्द्र सिंह भारती",
    nameEn: "Jitendra Singh Bharti",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "वाणिज्यिक कर अधिकारी (CTO)",
    postEn: "Commercial Tax Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "118",
    name: "जिनेन्द्रिय सागरिया",
    nameEn: "Jinendriya Sagariya",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "वाणिज्यिक कर अधिकारी (CTO)",
    postEn: "Commercial Tax Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "119",
    name: "प्रदीप कुमार गौतम",
    nameEn: "Pradeep Kumar Gautam",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "वाणिज्यिक कर अधिकारी (CTO)",
    postEn: "Commercial Tax Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "120",
    name: "अंकित राय",
    nameEn: "Ankit Rai",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "वाणिज्यिक कर अधिकारी (CTO)",
    postEn: "Commercial Tax Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "121",
    name: "शुभम दांगी",
    nameEn: "Shubham Dangi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी अधिकारी (Excise Officer)",
    postEn: "Excise Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "122",
    name: "पंकज लोखंडे",
    nameEn: "Pankaj Lokhande",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी अधिकारी (Excise Officer)",
    postEn: "Excise Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "123",
    name: "पायल असतकर",
    nameEn: "Payal Asatkar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक आयुक्त/संचालक",
    postEn: "Assistant Commissioner / Director",
    avatar: "",
    isRanker: false,
  },
  {
    id: "124",
    name: "अजय कुमार गोयल",
    nameEn: "Ajay Kumar Goel",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (Assistant Director)",
    postEn: "Assistant Director",
    avatar: "",
    isRanker: false,
  },
  {
    id: "125",
    name: "भूपेन्द्र सिंह बाकोड़े",
    nameEn: "Bhupendra Singh Bakode",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (Assistant Director)",
    postEn: "Assistant Director",
    avatar: "",
    isRanker: false,
  },
  {
    id: "126",
    name: "जमुना डुडवा",
    nameEn: "Jamuna Dudwa",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (स्कूल शिक्षा विभाग)",
    postEn: "Assistant Director (School Education)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "127",
    name: "बलवंत",
    nameEn: "Balwant",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (स्कूल शिक्षा विभाग)",
    postEn: "Assistant Director (School Education)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "128",
    name: "किरण कौशिक",
    nameEn: "Kiran Kaushik",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (स्कूल शिक्षा विभाग)",
    postEn: "Assistant Director (School Education)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "129",
    name: "सचिन मंडलोई",
    nameEn: "Sachin Mandloi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (स्कूल शिक्षा विभाग)",
    postEn: "Assistant Director (School Education)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "130",
    name: "जतिन पराशर",
    nameEn: "Jatin Parashar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (स्कूल शिक्षा विभाग)",
    postEn: "Assistant Director (School Education)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "131",
    name: "माधव खेर",
    nameEn: "Madhav Kher",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (स्कूल शिक्षा विभाग)",
    postEn: "Assistant Director (School Education)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "132",
    name: "दीपा किर",
    nameEn: "Deepa Kir",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (स्कूल शिक्षा विभाग)",
    postEn: "Assistant Director (School Education)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "133",
    name: "धनश्री जैन",
    nameEn: "Dhanshree Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (स्कूल शिक्षा विभाग)",
    postEn: "Assistant Director (School Education)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "134",
    name: "मधु शर्मा",
    nameEn: "Madhu Sharma",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (स्कूल शिक्षा विभाग)",
    postEn: "Assistant Director (School Education)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "135",
    name: "पूनम बकड़े",
    nameEn: "Poonam Bakde",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "136",
    name: "सत्यम चौरसिया",
    nameEn: "Satyam Chaurasia",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "137",
    name: "तेज सिंह राठौर",
    nameEn: "Tej Singh Rathore",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "138",
    name: "आयुषी बैरागी",
    nameEn: "Ayushi Bairagi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "139",
    name: "देवेन्द्र सिंह",
    nameEn: "Devendra Singh",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "140",
    name: "प्रशांत कुमार पांडे",
    nameEn: "Prashant Kumar Pandey",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "141",
    name: "प्रतीक यादव",
    nameEn: "Pratik Yadav",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "142",
    name: "रवि शंकर मिश्रा",
    nameEn: "Ravi Shankar Mishra",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "143",
    name: "शैलजा सिंह",
    nameEn: "Shailaja Singh",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "144",
    name: "संजय कुमार सुमन",
    nameEn: "Sanjay Kumar Suman",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "145",
    name: "शुभम अग्निहोत्री",
    nameEn: "Shubham Agnihotri",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (उद्योग एवं प्रबंधन)",
    postEn: "Assistant Director (Industry & Management)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "146",
    name: "रोहित भिण्डे",
    nameEn: "Rohit Bhinde",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक संचालक (स्कूल शिक्षा विभाग)",
    postEn: "Assistant Director (School Education)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "147",
    name: "अजय दांगी",
    nameEn: "Ajay Dangi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "विकास खंड अधिकारी (BDO)",
    postEn: "Block Development Officer (BDO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "148",
    name: "पंकज कुमार जाट",
    nameEn: "Pankaj Kumar Jat",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "विकास खंड अधिकारी (BDO)",
    postEn: "Block Development Officer (BDO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "149",
    name: "अंकिता पांडे",
    nameEn: "Ankita Pandey",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "150",
    name: "बिंदु तिवारी",
    nameEn: "Bindu Tiwari",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "151",
    name: "nishaंत चौरसिया",
    nameEn: "Nishant Chaurasia",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "152",
    name: "शशांक पालीवाल",
    nameEn: "Shashank Paliwal",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "153",
    name: "शिवम कुमार गौतम",
    nameEn: "Shivam Kumar Gautam",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "154",
    name: "शुभम गर्ग",
    nameEn: "Shubham Garg",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "155",
    name: "वर्षा पंवार",
    nameEn: "Varsha Panwar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "156",
    name: "आयुषोष गुप्ता",
    nameEn: "Ayushosh Gupta",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "157",
    name: "प्रज्ञा पाटीदार",
    nameEn: "Pragya Patidar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "158",
    name: "अयुषोष रामटेके",
    nameEn: "Ayushosh Ramteke",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "नायब तहसीलदार (Naib Tehsildar)",
    postEn: "Naib Tehsildar",
    avatar: "",
    isRanker: false,
  },
  {
    id: "159",
    name: "अंकित उडके",
    nameEn: "Ankit Udke",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक श्रम पदाधिकारी (Assistant Labour Officer)",
    postEn: "Assistant Labour Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "160",
    name: "अंकिता राय",
    nameEn: "Ankita Rai",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक श्रम पदाधिकारी (Assistant Labour Officer)",
    postEn: "Assistant Labour Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "161",
    name: "अधिनी रोजड़े",
    nameEn: "Adhini Rojde",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी उप-निरीक्षक (Excise Sub Inspector)",
    postEn: "Excise Sub Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "162",
    name: "भारती मरसे",
    nameEn: "Bharti Marse",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी उप-निरीक्षक (Excise Sub Inspector)",
    postEn: "Excise Sub Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "163",
    name: "मोहित बिरला",
    nameEn: "Mohit Birla",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी उप-निरीक्षक (Excise Sub Inspector)",
    postEn: "Excise Sub Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "164",
    name: "मुकुल सिंघाड़े",
    nameEn: "Mukul Singhade",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी उप-निरीक्षक (Excise Sub Inspector)",
    postEn: "Excise Sub Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "165",
    name: "सोनाली गुप्ता",
    nameEn: "Sonali Gupta",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी उप-निरीक्षक (Excise Sub Inspector)",
    postEn: "Excise Sub Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "166",
    name: "वर्षा राजपूत",
    nameEn: "Varsha Rajput",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी उप-निरीक्षक (Excise Sub Inspector)",
    postEn: "Excise Sub Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "167",
    name: "बृजराज शर्मा",
    nameEn: "Brijraj Sharma",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी उप-निरीक्षक (Excise Sub Inspector)",
    postEn: "Excise Sub Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "168",
    name: "योगेन्द्र सिंह",
    nameEn: "Yogendra Singh",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी उप-निरीक्षक (Excise Sub Inspector)",
    postEn: "Excise Sub Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "169",
    name: "अंजली तिवारी",
    nameEn: "Anjali Tiwari",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "आबकारी उप-निरीक्षक (Excise Sub Inspector)",
    postEn: "Excise Sub Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "170",
    name: "रविन्द्र सोलंकी",
    nameEn: "Ravindra Solanki",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "171",
    name: "अंकित सोनी",
    nameEn: "Ankit Soni",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "172",
    name: "गजेन्द्र प्रसाद नागपुरे",
    nameEn: "Gajendra Prasad Nagpure",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "173",
    name: "गजेन्द्र सिंह लोधी",
    nameEn: "Gajendra Singh Lodhi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "174",
    name: "किरण हंगाळे",
    nameEn: "Kiran Hangale",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "175",
    name: "प्रवीण मुकाती",
    nameEn: "Pravin Mukati",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "176",
    name: "रंजना गोयल",
    nameEn: "Ranjana Goel",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "177",
    name: "अर्चना मरावी",
    nameEn: "Archana Maravi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "178",
    name: "अधिनी कुमारे",
    nameEn: "Adhini Kumare",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "179",
    name: "चित्रलेखा मरावी",
    nameEn: "Chitralekha Maravi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "180",
    name: "जयेश पाटीदार",
    nameEn: "Jayesh Patidar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "181",
    name: "पूजा तिवारी",
    nameEn: "Pooja Tiwari",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "182",
    name: "रामहेत सिंह बैस",
    nameEn: "Ramhet Singh Bais",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "183",
    name: "श्वेता मिगल",
    nameEn: "Shweta Migal",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "184",
    name: "यश गुप्ता",
    nameEn: "Yash Gupta",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "185",
    name: "अमित अग्निहोत्री",
    nameEn: "Amit Agnihotri",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "186",
    name: "सुनील कुमार मीणा",
    nameEn: "Sunil Kumar Meena",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "187",
    name: "प्रांजल त्रिपाठी",
    nameEn: "Pranjal Tripathi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "188",
    name: "आयुषी खन्ना",
    nameEn: "Ayushi Khanna",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "189",
    name: "अक्षवी पाटीदार",
    nameEn: "Akshavi Patidar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "190",
    name: "दिव्या यादव",
    nameEn: "Divya Yadav",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "191",
    name: "भानु किरार",
    nameEn: "Bhanu Kirar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "192",
    name: "सुधीर कुमार",
    nameEn: "Sudhir Kumar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "193",
    name: "योगेश कुशराम",
    nameEn: "Yogesh Kushram",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "194",
    name: "प्रतीका गोस्वामी",
    nameEn: "Pratika Goswami",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "195",
    name: "ज्योति वर्मा",
    nameEn: "Jyoti Verma",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "196",
    name: "सजल सक्सेना",
    nameEn: "Sajal Saxena",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "197",
    name: "गौतम वर्मे",
    nameEn: "Gautam Varme",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "198",
    name: "सत्यम जाट",
    nameEn: "Satyam Jat",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "199",
    name: "विजय कुमार रजक",
    nameEn: "Vijay Kumar Rajak",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "200",
    name: "शशांक जैन",
    nameEn: "Shashank Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "म.प्र. अधीनस्थ लेखा सेवा",
    postEn: "MP Subordinate Accounts Service",
    avatar: "",
    isRanker: false,
  },
  {
    id: "201",
    name: "उदेश्री चौहान",
    nameEn: "Udeshree Chauhan",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक निरीक्षक (वित्त)",
    postEn: "Assistant Inspector (Finance)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "202",
    name: "सजल जैन",
    nameEn: "Sajal Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक निरीक्षक (वित्त)",
    postEn: "Assistant Inspector (Finance)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "203",
    name: "निक्षया बघेल",
    nameEn: "Nikshaya Baghel",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक निरीक्षक (वित्त)",
    postEn: "Assistant Inspector (Finance)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "204",
    name: "रौशनी पंवार",
    nameEn: "Roshni Panwar",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक निरीक्षक (वित्त)",
    postEn: "Assistant Inspector (Finance)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "205",
    name: "राशि जैन",
    nameEn: "Rashi Jain",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक निरीक्षक (वित्त)",
    postEn: "Assistant Inspector (Finance)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "206",
    name: "सुशी सुर्खेल",
    nameEn: "Sushi Surkhel",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहायक निरीक्षक (वित्त)",
    postEn: "Assistant Inspector (Finance)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "207",
    name: "अनोष्का सिंहारे",
    nameEn: "Anoshka Singhare",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "वाणिज्यिक कर अधिकारी (CTO)",
    postEn: "Commercial Tax Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "208",
    name: "निराशा यादव",
    nameEn: "Nirasha Yadav",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "वाणिज्यिक कर अधिकारी (CTO)",
    postEn: "Commercial Tax Officer",
    avatar: "",
    isRanker: false,
  },
  {
    id: "209",
    name: "अंकित परिहारिया",
    nameEn: "Ankit Parihariya",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "जनपद पंचायत सीईओ (Janpad Panchayat CEO)",
    postEn: "Janpad Panchayat CEO",
    avatar: "",
    isRanker: false,
  },
  {
    id: "210",
    name: "सोमेश",
    nameEn: "Somesh",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "211",
    name: "अक्षय गर्ग",
    nameEn: "Akshay Garg",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "212",
    name: "योगेश वर्मी",
    nameEn: "Yogesh Varmi",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "मुख्य नगर पालिका अधिकारी (CMO)",
    postEn: "Chief Municipal Officer (CMO)",
    avatar: "",
    isRanker: false,
  },
  {
    id: "213",
    name: "आदित्य शुक्ला",
    nameEn: "Aditya Shukla",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "214",
    name: "देशराज राजपूत",
    nameEn: "Deshraj Rajput",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "215",
    name: "प्रदीप सिंह रावत",
    nameEn: "Pradeep Singh Rawat",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "216",
    name: "सुचंद बघेल",
    nameEn: "Suchand Baghel",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  },
  {
    id: "217",
    name: "नीलम पनिका",
    nameEn: "Neelam Panika",
    rank: 0,
    exam: "MPPSC",
    year: 2023,
    post: "सहकारिता निरीक्षक (Cooperative Inspector)",
    postEn: "Cooperative Inspector",
    avatar: "",
    isRanker: false,
  }
];

export function SelectionsClient({ locale, initialSelections = [] }: SelectionsClientProps) {
  const isHi = locale === "hi";

  // Fallback to static data if no Sanity data is available yet
  const selectionsData = useMemo(() => {
    return initialSelections.length > 0 ? initialSelections : TOPPERS_DATA;
  }, [initialSelections]);

  // Filter States
  const [activeExam, setActiveExam] = useState<"ALL" | "UPSC" | "MPPSC">("ALL");
  const [activeYear, setActiveYear] = useState<string>("ALL");
  const [searchQuery, setSearchQuery] = useState<string>("");

  // Get distinct years
  const availableYears = useMemo(() => {
    const years = selectionsData.map((t) => t.year.toString());
    return ["ALL", ...Array.from(new Set(years)).sort((a, b) => b.localeCompare(a))];
  }, [selectionsData]);

  // Filter rankers featured in "Our Rankers"
  const rankers = useMemo(() => {
    return selectionsData.filter((t) => t.isRanker);
  }, [selectionsData]);

  // Filter other selections dynamically
  const filteredSelections = useMemo(() => {
    return selectionsData.filter((t) => {
      const matchExam = activeExam === "ALL" || t.exam === activeExam;
      const matchYear = activeYear === "ALL" || t.year.toString() === activeYear;
      
      const name = isHi ? t.name : t.nameEn;
      const post = isHi ? t.post : t.postEn;
      const matchSearch =
        searchQuery === "" ||
        name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        post.toLowerCase().includes(searchQuery.toLowerCase()) ||
        t.rank.toString() === searchQuery ||
        (t.rollNo && t.rollNo.toLowerCase().includes(searchQuery.toLowerCase()));

      return matchExam && matchYear && matchSearch;
    });
  }, [activeExam, activeYear, searchQuery, isHi, selectionsData]);

  return (
    <div className="space-y-16 pb-20">
      
      {/* ─── HERO SECTION ─── */}
      <section className="relative overflow-hidden bg-gradient-to-br from-primary/5 via-accent/5 to-transparent py-16 sm:py-24 border-b border-border/50">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,_var(--primary)_0%,_transparent_50%)] opacity-30 pointer-events-none" />
        <Container size="wide" className="text-center relative z-10 space-y-6">
          <div className="mx-auto w-fit rounded-full bg-primary/10 border border-primary/20 px-4 py-1.5 text-xs font-bold text-primary flex items-center gap-1.5 animate-pulse">
            <Trophy className="h-4 w-4" />
            <span>{isHi ? "सफलता की बेजोड़ विरासत" : "Unrivaled Legacy of Success"}</span>
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-foreground max-w-3xl mx-auto">
            {isHi ? "हमारे MPPSC टॉपर्स और चयन सूची" : "Our MPPSC Toppers & Selections list"}
          </h1>
          <p className="text-sm sm:text-base text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            {isHi 
              ? "आकार IAS ने कड़ी मेहनत, उत्कृष्ट मार्गदर्शन और प्रतिबद्धता के साथ सैकड़ों सिविल सेवकों के सपनों को साकार किया है। यहाँ हमारे श्रेष्ठ रैंकर्स की सफलता की झलक है।"
              : "With hard work, exceptional mentorship, and dedication, Aakar IAS has turned the dreams of hundreds of civil service aspirants into reality. Here is a glimpse of our stellar achievers."}
          </p>
          
          {/* Highlight Stats */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 max-w-3xl mx-auto pt-8">
            {[
              { val: isHi ? "2 लाख+" : "2L+", title: isHi ? "छात्र (STUDENTS)" : "STUDENTS" },
              { val: "2000+", title: isHi ? "चयन (SELECTIONS)" : "SELECTIONS" },
              { val: "11+", title: isHi ? "वर्ष (YEARS)" : "YEARS" },
            ].map((stat, i) => (
              <div key={i} className="bg-card border border-border p-5 rounded-2xl shadow-soft">
                <p className="text-3xl sm:text-4xl font-extrabold text-primary">{stat.val}</p>
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mt-1">{stat.title}</p>
              </div>
            ))}
          </div>
        </Container>
      </section>

      {/* ─── SECTION 1: OUR RANKERS ─── */}
      <section className="bg-background">
        <Container size="wide" className="space-y-10">
          <div className="text-center space-y-2">
            <h2 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-foreground flex items-center justify-center gap-2">
              <Sparkles className="h-6 w-6 text-primary" />
              <span>{isHi ? "हमारे शीर्ष रैंकर्स" : "Our Rankers"}</span>
            </h2>
            <p className="text-xs sm:text-sm text-muted-foreground">
              {isHi ? "सिविल सेवा परीक्षाओं में सर्वोच्च मुकाम हासिल करने वाले सितारे" : "Stars who achieved top ranks in civil service examinations"}
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {rankers.map((topper, i) => (
              <div 
                key={i} 
                className={cn(
                  "bg-card border rounded-3xl p-6 sm:p-8 relative shadow-soft hover:shadow-soft-lg transition-all group flex flex-col justify-between overflow-hidden",
                  topper.rank === 1
                    ? "border-amber-500/60 ring-1 ring-amber-500/20 bg-gradient-to-br from-card via-amber-500/[0.02] to-card"
                    : "border-border/80"
                )}
              >
                {/* Gold light effect for rank 1 */}
                {topper.rank === 1 && (
                  <div className="absolute -right-16 -top-16 w-36 h-36 bg-amber-500/10 rounded-full blur-2xl pointer-events-none" />
                )}
                
                {/* Accent design line */}
                <div className={cn(
                  "absolute top-0 left-10 right-10 h-[3px] rounded-full opacity-75",
                  topper.rank === 1 ? "bg-gradient-to-r from-amber-400 to-orange-500" : "bg-gradient-to-r from-primary to-accent"
                )} />
                
                <div className="space-y-5">
                  {/* Badge & Rank */}
                  <div className="flex justify-between items-start">
                    <span className={cn(
                      "px-3 py-1 rounded-full text-[10px] font-bold tracking-wider text-white",
                      topper.exam === "UPSC" ? "bg-blue-600" : "bg-green-600"
                    )}>
                      {topper.exam} • {topper.year}
                    </span>
                    {topper.rank === 1 ? (
                      <div className="flex items-center gap-1 bg-amber-500/10 border border-amber-500/30 px-3 py-1 rounded-full text-[10px] font-extrabold text-amber-600">
                        <Trophy className="h-3.5 w-3.5 text-amber-500 animate-bounce" />
                        <span>{isHi ? "1st रैंक (Classroom)" : "1st Rank (Classroom)"}</span>
                      </div>
                    ) : (
                      <div className="flex items-center gap-1 bg-primary/10 border border-primary/20 px-3 py-1 rounded-full text-[10px] font-extrabold text-primary">
                        <Medal className="h-3.5 w-3.5" />
                        <span>Rank {topper.rank}</span>
                      </div>
                    )}
                  </div>

                  {/* Large Portrait Topper Image Block */}
                  <div className={cn(
                    "w-full aspect-[4/3] rounded-2xl border overflow-hidden relative flex items-center justify-center bg-gradient-to-br shadow-inner",
                    topper.rank === 1 ? "border-amber-400/80 bg-amber-500/[0.05]" : "border-primary/20 bg-muted/40"
                  )}>
                    {topper.avatar ? (
                      <Image
                        src={topper.avatar}
                        alt={isHi ? topper.name : topper.nameEn}
                        fill
                        className="object-cover object-top group-hover:scale-105 transition-transform duration-500"
                      />
                    ) : (
                      <div className="flex flex-col items-center gap-2 text-center text-amber-500/30">
                        <GraduationCap className="h-14 w-14" />
                        <span className="text-[9px] font-extrabold uppercase tracking-widest text-amber-600/40">
                          {isHi ? "फोटो (Photo)" : "Photo Pending"}
                        </span>
                      </div>
                    )}

                    {/* Left corner 1st rank visual graphic overlay */}
                    {topper.rank === 1 && (
                      <div className="absolute top-4 left-4 bg-orange-600 text-white text-[9px] font-extrabold px-2.5 py-1 rounded-lg uppercase tracking-wider shadow-md">
                        {isHi ? "क्लासरूम" : "From Classroom"}
                      </div>
                    )}
                  </div>

                  {/* Profile Info */}
                  <div className="space-y-1">
                    <h3 className="font-extrabold text-foreground text-lg leading-tight group-hover:text-primary transition-colors">
                      {isHi ? topper.name : topper.nameEn}
                    </h3>
                    <p className="text-xs text-muted-foreground font-bold">
                      {isHi ? topper.post : topper.postEn}
                    </p>
                  </div>

                  {/* Testimonial Quote */}
                  {(topper.quote || topper.quoteEn) && (
                    <blockquote className="text-xs sm:text-sm text-muted-foreground italic leading-relaxed bg-muted/30 border-l-2 border-primary/40 pl-4 py-1.5 mt-3">
                      &ldquo;{isHi ? topper.quote : topper.quoteEn}&rdquo;
                    </blockquote>
                  )}
                </div>

                {topper.rollNo && (
                  <div className="mt-6 pt-4 border-t border-border/50 text-[10px] text-muted-foreground font-semibold uppercase tracking-wider flex justify-end">
                    <span className="text-primary group-hover:translate-x-1 transition-transform inline-flex items-center gap-0.5">
                      Verified <UserCheck className="h-3.5 w-3.5 ml-1" />
                    </span>
                  </div>
                )}
              </div>
            ))}
          </div>
        </Container>
      </section>

      {/* ─── SECTION 2: OUR ALL SELECTIONS ─── */}
      <section className="bg-background">
        <Container size="wide" className="space-y-8">
          
          <div className="border-b border-border/60 pb-6 flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
            <div className="space-y-1">
              <h2 className="text-xl sm:text-2xl font-extrabold tracking-tight text-foreground flex items-center gap-2">
                <Award className="h-5.5 w-5.5 text-primary" />
                <span>{isHi ? "हमारे सभी चयन" : "Our All Selections"}</span>
              </h2>
              <p className="text-xs text-muted-foreground">
                {isHi ? "वर्षवार और परीक्षावार सफल अभ्यर्थियों की पूरी सूची" : "Complete list of successful candidates filtered by year and exam"}
              </p>
            </div>

            {/* Interactive Filters Grid */}
            <div className="flex flex-wrap items-center gap-3 w-full md:w-auto">
              
              {/* Search Box */}
              <div className="relative flex-1 md:flex-none min-w-[200px]">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <input
                  type="text"
                  placeholder={isHi ? "नाम, रैंक या पद खोजें..." : "Search name, rank or post..."}
                  className="pl-9 pr-4 py-2 text-xs font-semibold rounded-xl border border-border bg-card text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary w-full"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
              </div>

              {/* Exam Filter tabs */}
              <div className="flex bg-muted/40 p-1 border border-border/50 rounded-xl text-xs font-bold shrink-0">
                {(["ALL", "UPSC", "MPPSC"] as const).map((exam) => (
                  <button
                    key={exam}
                    onClick={() => setActiveExam(exam)}
                    className={cn(
                      "px-3 py-1.5 rounded-lg transition-colors cursor-pointer",
                      activeExam === exam 
                        ? "bg-primary text-primary-foreground shadow-soft-sm" 
                        : "text-muted-foreground hover:text-foreground hover:bg-muted"
                    )}
                  >
                    {exam === "ALL" ? (isHi ? "सभी" : "All") : exam}
                  </button>
                ))}
              </div>

              {/* Year Select dropdown */}
              <div className="relative shrink-0">
                <select
                  value={activeYear}
                  onChange={(e) => setActiveYear(e.target.value)}
                  className="appearance-none bg-card border border-border px-4 py-2 rounded-xl text-xs font-bold text-foreground focus:outline-none focus:ring-1 focus:ring-primary cursor-pointer pr-8"
                >
                  {availableYears.map((y) => (
                    <option key={y} value={y}>
                      {y === "ALL" ? (isHi ? "सभी वर्ष" : "All Years") : y}
                    </option>
                  ))}
                </select>
                <span className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-muted-foreground text-xs">▼</span>
              </div>

            </div>
          </div>

          {/* Selections Render Grid */}
          {filteredSelections.length > 0 ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {filteredSelections.map((topper, i) => (
                <div 
                  key={i} 
                  className="bg-card border border-border p-4 rounded-2xl shadow-soft hover:shadow-soft-lg transition-all flex flex-col justify-between space-y-3"
                >
                  <div className="space-y-3">
                    {/* Medium Topper Image Block */}
                    <div className="relative w-full aspect-[16/10] rounded-xl overflow-hidden border border-border/40 bg-muted/20 flex items-center justify-center">
                      {topper.avatar ? (
                        <Image
                          src={topper.avatar}
                          alt={isHi ? topper.name : topper.nameEn}
                          fill
                          className="object-cover object-top"
                        />
                      ) : (
                        <div className="flex flex-col items-center gap-1 text-muted-foreground/30">
                          <GraduationCap className="h-8 w-8" />
                          <span className="text-[8px] font-bold uppercase tracking-wider">Photo</span>
                        </div>
                      )}
                    </div>

                    <div className="flex justify-between items-start">
                      <div className="flex items-center gap-1">
                        <span className={cn(
                          "w-1.5 h-1.5 rounded-full",
                          topper.exam === "UPSC" ? "bg-blue-600" : "bg-green-600"
                        )} />
                        <span className="text-[9px] font-bold text-muted-foreground tracking-wider uppercase">
                          {topper.isRanker ? `${topper.exam} • ${topper.year}` : topper.exam}
                        </span>
                      </div>
                      {topper.isRanker && (
                        <span className="bg-primary/5 px-2 py-0.5 rounded text-[9px] font-extrabold text-primary">
                          Rank {topper.rank}
                        </span>
                      )}
                    </div>

                    <div>
                      <h4 className="font-extrabold text-foreground text-sm line-clamp-1">
                        {isHi ? topper.name : topper.nameEn}
                      </h4>
                      <p className="text-xs text-muted-foreground mt-0.5 line-clamp-1 font-semibold">
                        {isHi ? topper.post : topper.postEn}
                      </p>
                    </div>
                  </div>

                  {topper.rollNo && (
                    <div className="border-t border-border/50 pt-2 flex justify-end items-center text-[9px] text-muted-foreground font-semibold">
                      <span className="text-primary-fixed-dim">Verified</span>
                    </div>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-16 bg-card border border-dashed border-border rounded-2xl space-y-3">
              <UserCheck className="h-12 w-12 text-muted-foreground mx-auto" />
              <h4 className="font-bold text-foreground">
                {isHi ? "कोई रिकॉर्ड नहीं मिला" : "No Records Found"}
              </h4>
              <p className="text-xs text-muted-foreground max-w-sm mx-auto">
                {isHi 
                  ? "कृपया अपना सर्च शब्द बदलें या दूसरा फ़िल्टर चुनें।"
                  : "Please adjust your search terms or try selecting another filter."}
              </p>
            </div>
          )}

        </Container>
      </section>

      {/* ─── CALL TO ACTION BANNER ─── */}
      <section className="bg-background">
        <Container size="wide">
          <div className="bg-primary/5 border border-primary/10 rounded-3xl p-8 sm:p-12 relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="space-y-4 max-w-2xl text-center md:text-left">
              <h3 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-foreground">
                {isHi ? "अगला नाम आपका हो सकता है!" : "Your Name Could Be Next!"}
              </h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {isHi 
                  ? "आकार IAS के एक्सपर्ट मेंटर्स, टेस्ट सीरीज और पर्सनलाइज्ड स्टडी प्लान के साथ अपनी सिविल सेवा परीक्षा की तैयारी को सही दिशा दें।"
                  : "Empower your civil services preparation with expert guidance, top-tier test series, and personalized study plans from Aakar IAS."}
              </p>
            </div>
            <Link href={isHi ? "/contact" : "/en/contact"}>
              <Button className="rounded-xl px-8 py-6 font-bold flex items-center gap-2 group shrink-0">
                <span>{isHi ? "परामर्श सत्र बुक करें" : "Book Counseling"}</span>
                <ArrowRight className="h-4 w-4 group-hover:translate-x-1 transition-transform" />
              </Button>
            </Link>
          </div>
        </Container>
      </section>

    </div>
  );
}
