import { createClient } from "@sanity/client";
import dotenv from "dotenv";
import path from "path";
import fs from "fs";

// Load env.local explicitly
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const {
  NEXT_PUBLIC_SANITY_PROJECT_ID: projectId,
  NEXT_PUBLIC_SANITY_DATASET: dataset,
  SANITY_API_WRITE_TOKEN: token,
} = process.env;

if (!projectId || !dataset || !token) {
  console.error("❌ Missing Sanity variables in .env.local!");
  process.exit(1);
}

const client = createClient({
  projectId,
  dataset,
  token,
  apiVersion: "2024-10-01",
  useCdn: false,
});

// Helper to convert an array of strings into separate Portable Text blocks
function createBlocks(items: string[]): any[] {
  return items.map((text, idx) => {
    const randomSuffix = Math.random().toString(36).substring(2, 9);
    return {
      _key: `block-${idx}-${randomSuffix}`,
      _type: "block",
      style: "normal",
      children: [
        {
          _key: `span-${idx}-${randomSuffix}`,
          _type: "span",
          text: text,
        },
      ],
    };
  });
}

// Helper to create a custom block with a link
function createLinkBlock(textBefore: string, linkText: string, textAfter: string, url: string): any {
  const randomSuffix = Math.random().toString(36).substring(2, 9);
  return {
    _key: `block-link-${randomSuffix}`,
    _type: "block",
    style: "normal",
    children: [
      {
        _key: `span-before-${randomSuffix}`,
        _type: "span",
        text: textBefore,
      },
      {
        _key: `span-link-${randomSuffix}`,
        _type: "span",
        text: `[${linkText}](${url})`,
      },
      {
        _key: `span-after-${randomSuffix}`,
        _type: "span",
        text: textAfter,
      }
    ]
  };
}

// Helper to create a custom table block
function createTable(key: string, caption: string, headers: string[], rows: string[][]): any {
  return {
    _key: key,
    _type: "table",
    table: {
      caption,
      headers,
      rows,
    },
  };
}

async function main() {
  console.log("🚀 Starting upload process for ODOP Scheme 2026 Current Affairs Article...");

  // Image files generated by the generate_image tool
  const imagePaths = {
    banner: path.resolve(process.cwd(), "/Users/aakariastech/.gemini/antigravity-ide/brain/f3368bc5-9762-4cc4-a6af-e2c9e58d3968/odop_india_banner_1784204050975.png"),
    showcase: path.resolve(process.cwd(), "/Users/aakariastech/.gemini/antigravity-ide/brain/f3368bc5-9762-4cc4-a6af-e2c9e58d3968/odop_mp_showcase_1784204066214.png"),
  };

  // Check if files exist
  if (!fs.existsSync(imagePaths.banner) || !fs.existsSync(imagePaths.showcase)) {
    console.error("❌ Required images not found in the generated paths!");
    process.exit(1);
  }

  // 1. Upload Banner Image (India ODOP Banner)
  console.log("📸 Uploading banner image...");
  const assetBanner = await client.assets.upload("image", fs.createReadStream(imagePaths.banner), {
    filename: "odop_india_banner.png",
  });
  console.log(`✔ Uploaded banner image. Asset ID: ${assetBanner._id}`);

  // 2. Upload Showcase Image (MP ODOP products)
  console.log("📸 Uploading showcase image...");
  const assetShowcase = await client.assets.upload("image", fs.createReadStream(imagePaths.showcase), {
    filename: "odop_mp_showcase.png",
  });
  console.log(`✔ Uploaded showcase image. Asset ID: ${assetShowcase._id}`);

  // 3. Construct the Article document with _type: "currentAffairs"
  const article = {
    _id: "ca-one-district-one-product-odop-scheme-2026",
    _type: "currentAffairs",
    slug: { _type: "slug", current: "one-district-one-product-odop-scheme-2026" },
    title: "एक जिला-एक उत्पाद (ODOP) योजना: स्थानीय उत्पादों को वैश्विक पहचान देने की भारत सरकार की पहल",
    titleEn: "One District One Product (ODOP) Scheme: Promoting Local Specialties for a Global Footprint",
    excerpt: "भारत सरकार की 'एक जिला-एक उत्पाद' (ODOP) योजना देश के हर जिले की पारंपरिक, हस्तशिल्प और कृषि विरासत को सशक्त बनाकर निर्यात और ग्रामीण अर्थव्यवस्था को मजबूत करने का कार्य कर रही है।",
    excerptEn: "The central government's 'One District One Product' (ODOP) initiative aims to foster balanced regional development by promoting unique local handicrafts, agriculture, and industries of every district.",
    ca_date: "2026-07-16",
    publishedAt: new Date().toISOString(),
    featured: true,
    readingTime: 6,
    keywords: [
      "One District One Product",
      "ODOP Scheme India",
      "ODOP Madhya Pradesh list",
      "PMFME Scheme",
      "Vocal for Local",
      "Atmanirbhar Bharat Initiative",
      "UPSC Government Schemes",
      "MPPSC GK Current Affairs",
      "एक जिला एक उत्पाद योजना",
      "ओडीओपी मध्य प्रदेश सूची",
      "वोकल फॉर लोकल भारत",
      "आत्मनिर्भर भारत अभियान"
    ],
    category: { _type: "reference", _ref: "cat-mpgk" },
    author: { _type: "reference", _ref: "author-aakar" },
    tags: [
      { _type: "reference", _ref: "tag-upsc" },
      { _type: "reference", _ref: "tag-mppsc" },
      { _type: "reference", _ref: "tag-prelims" },
      { _type: "reference", _ref: "tag-mains" },
      { _type: "reference", _ref: "tag-mp-ca" }, // MP Current Affairs
    ],
    syllabus: ["GS-3", "Prelims-GS"],
    featuredImage: {
      _type: "image",
      asset: { _type: "reference", _ref: assetBanner._id },
      alt: "A professional banner for One District One Product (ODOP) scheme showing various regional products of India",
    },
    sections: [
      /* Section 1: Context */
      {
        _key: "sec-context",
        kind: "whyInNews",
        title: "प्रसंग (Context)",
        titleEn: "Why in News?",
        body: createBlocks([
          "भारत की पहचान उसकी विविध संस्कृति, पारंपरिक हस्तशिल्प, कृषि उत्पादों और स्थानीय उद्योगों से है। देश का लगभग हर जिला किसी न किसी विशिष्ट उत्पाद के लिए प्रसिद्ध है। इन्हीं स्थानीय उत्पादों को राष्ट्रीय और अंतरराष्ट्रीय स्तर पर पहचान दिलाने के उद्देश्य से भारत सरकार ने 'एक जिला-एक उत्पाद' (One District One Product – ODOP) पहल को अत्यधिक बढ़ावा दिया है। यह योजना स्थानीय उत्पादों की ब्रांडिंग, विपणन, निर्यात और रोजगार सृजन के माध्यम से 'वोकल फॉर लोकल' और 'आत्मनिर्भर भारत' के लक्ष्य को मजबूत करती है।"
        ]),
        bodyEn: createBlocks([
          "India's identity is deeply rooted in its diverse culture, traditional handicrafts, agricultural products, and micro-industries. Nearly every district across the country is renowned for a specific specialty. To grant these local products national and global recognition, the Government of India has heavily promoted the 'One District One Product' (ODOP) initiative. Through branding, modern packaging, exports, and rural job creation, this scheme bolsters the twin targets of 'Vocal for Local' and 'Atmanirbhar Bharat'."
        ]),
      },

      /* Section 2: Interlinking */
      {
        _key: "sec-related-articles",
        kind: "timeline",
        title: "संबंधित लेख अवश्य पढ़ें (Important References)",
        titleEn: "Important Related Articles",
        body: [
          createLinkBlock(
            "• ",
            "पद्मश्री डॉ. रजनीकांत: 'GI Man of India' (पूरी जीवनी)",
            " — पारंपरिक शिल्प को संरक्षण दिलाने वाले नायक।",
            "/current-affairs/dr-rajnikant-gi-man-of-india"
          ),
          createLinkBlock(
            "• ",
            "जबलपुर के मटर और सिंघाड़ा को मिला GI टैग",
            " — नर्मदा घाटी की कृषि विरासत को मिला सम्मान।",
            "/current-affairs/jabalpur-matar-singhada-gi-tag-2026"
          ),
          createLinkBlock(
            "• ",
            "नाबार्ड (NABARD) द्वारा 28 नए उत्पादों को GI टैग",
            " — भारत के पंजीकृत जीआई उत्पादों का पूरा विवरण।",
            "/general-awareness/nabard-28-new-gi-tags-2026"
          ),
          createLinkBlock(
            "• ",
            "मध्य प्रदेश की चार आदिवासी फसलों को मिला GI टैग",
            " — जनजातीय कृषि विरासत का संरक्षण।",
            "/current-affairs/mp-tribal-crops-gi-2026"
          )
        ],
        bodyEn: [
          createLinkBlock(
            "• ",
            "Padmashree Dr. Rajnikant: 'GI Man of India' (Biography)",
            " — The pioneer safeguarding traditional Indian arts.",
            "/current-affairs/dr-rajnikant-gi-man-of-india"
          ),
          createLinkBlock(
            "• ",
            "Jabalpur Peas and Water Chestnut GI Tag",
            " — Agricultural milestone for Narmada Valley region.",
            "/current-affairs/jabalpur-matar-singhada-gi-tag-2026"
          ),
          createLinkBlock(
            "• ",
            "NABARD Facilitates GI Tags for 28 New Products",
            " — Comprehensive list of newly registered crafts.",
            "/general-awareness/nabard-28-new-gi-tags-2026"
          ),
          createLinkBlock(
            "• ",
            "4 Tribal Crops of Madhya Pradesh Secure GI Tags",
            " — Preserving indigenous tribal agricultural varieties.",
            "/current-affairs/mp-tribal-crops-gi-2026"
          )
        ],
      },

      /* Section 3: What is ODOP */
      {
        _key: "sec-what-is-odop",
        kind: "background",
        title: "ODOP (One District One Product) क्या है?",
        titleEn: "What is One District One Product (ODOP)?",
        body: createBlocks([
          "One District One Product (ODOP) भारत सरकार की एक प्रमुख विकासात्मक पहल है, जिसके अंतर्गत प्रत्येक जिले की एक विशिष्ट पारंपरिक, कृषि, हस्तशिल्प या औद्योगिक उत्पाद को पहचान देकर उसके उत्पादन, ब्रांडिंग, विपणन और निर्यात को बढ़ावा दिया जाता है। इस योजना का उद्देश्य केवल उत्पाद को पहचान देना नहीं, बल्कि उससे जुड़े किसानों, कारीगरों, महिला स्वयं सहायता समूहों (SHGs), सूक्ष्म एवं लघु उद्योगों और स्थानीय उद्यमियों की आय बढ़ाना भी है।"
        ]),
        bodyEn: createBlocks([
          "One District One Product (ODOP) is a transformative initiative by the Government of India aimed at identifying, developing, and promoting one unique agricultural, handicraft, handloom, or industrial product from each district. The core vision is to convert every district into an export hub, improving the incomes of local farmers, artisans, weavers, Self-Help Groups (SHGs), and micro-entrepreneurs."
        ]),
      },

      /* Section 4: Origin and Launch */
      {
        _key: "sec-origin-launch",
        kind: "keyHighlights",
        title: "योजना की उत्पत्ति और भारत में शुरुआत",
        titleEn: "Origin of Concept and Launch in India",
        body: createBlocks([
          "• जापानी मॉडल: ODOP की मूल अवधारणा वर्ष 1979 में जापान के ओइता (Oita) प्रांत के तत्कालीन गवर्नर मोरीहिको हिरामत्सू द्वारा शुरू की गई 'वन विलेज वन प्रोडक्ट' (One Village One Product - OVOP) योजना से प्रेरित है।",
          "• उत्तर प्रदेश में शुरुआत: भारत में इस अवधारणा को सबसे पहले उत्तर प्रदेश सरकार ने जनवरी 2018 में अपने स्थापना दिवस पर राज्य स्तर पर लागू किया था।",
          "• राष्ट्रीय स्तर पर क्रियान्वयन: उत्तर प्रदेश मॉडल की बड़ी सफलता को देखते हुए, भारत सरकार ने वर्ष 2020 में इसे 'प्रधानमंत्री सूक्ष्म खाद्य प्रसंस्करण उद्यम औपचारीकरण योजना' (PMFME Scheme) के तहत पूरे देश में लागू किया। इसका नेतृत्व वाणिज्य एवं उद्योग मंत्रालय का DPIIT विभाग कर रहा है।"
        ]),
        bodyEn: createBlocks([
          "• Japanese OVOP Model: The core concept of ODOP draws inspiration from the 'One Village One Product' (OVOP) program launched in Oita Prefecture, Japan in 1979 by Governor Morihiko Hiramatsu.",
          "• Uttar Pradesh - The Pioneer: Uttar Pradesh was the first Indian state to formally launch the ODOP scheme in January 2018 on its foundation day to revive local traditional crafts.",
          "• National Scale-up: Following the success of the UP model, the Government of India extended it nationwide in 2020. It is integrated under the PMFME scheme and administered by the Department for Promotion of Industry and Internal Trade (DPIIT) under the Ministry of Commerce and Industry."
        ]),
      },

      /* Section 5: Difference between ODOP and GI Tag */
      {
        _key: "sec-odop-vs-gitag",
        kind: "governmentInitiatives",
        title: "ODOP और GI टैग (Geographical Indication) में अंतर",
        titleEn: "Difference Between ODOP and GI Tag",
        body: [
          ...createBlocks([
            "छात्रों को अक्सर इन दोनों अवधारणाओं में असमंजस रहता है, इनका अंतर समझना परीक्षा के लिए महत्वपूर्ण है:",
            "• एक जिला-एक उत्पाद (ODOP): यह सरकार की एक आर्थिक और औद्योगिक विकास योजना है। इसका मुख्य जोर जिले के किसी भी चुनिंदा उत्पाद के उत्पादन विस्तार, आधुनिक मशीनरी, पैकेजिंग, सब्सिडी और विपणन (Marketing) पर होता है।",
            "• भौगोलिक संकेतक (GI Tag): यह एक कानूनी बौद्धिक संपदा अधिकार (IPR) है। यह केवल उन्हीं उत्पादों को मिलता है जिनकी विशिष्ट गुणवत्ता, साख या विशेषताएं उनके विशिष्ट भौगोलिक क्षेत्र, जलवायु और मिट्टी पर निर्भर करती हैं। यह नकली उत्पादों की बिक्री के खिलाफ कानूनी संरक्षण प्रदान करता है।"
          ]),
          createTable(
            "table-odop-vs-gi-hi",
            "ODOP बनाम GI टैग तुलना",
            ["मापदंड (Parameter)", "एक जिला-एक उत्पाद (ODOP)", "भौगोलिक संकेतक (GI Tag)"],
            [
              ["प्रकृति", "सरकारी आर्थिक एवं विपणन विकास योजना", "कानूनी बौद्धिक संपदा अधिकार (IPR)"],
              ["केंद्रित बिंदु", "उत्पादन बढ़ाना, पैकेजिंग और वित्तीय सहायता", "उत्पाद की मौलिकता एवं विशिष्ट भौगोलिक उत्पत्ति की सुरक्षा"],
              ["कानूनी आधार", "विभागीय नीतियां और सरकारी बजटीय सहायता", "जीआई पंजीकरण अधिनियम, 1999 के तहत विधिक मान्यता"],
              ["वैधता अवधि", "योजना की सरकारी अवधि तक", "पंजीकरण के बाद 10 वर्ष तक वैध (नवीकरणीय)"]
            ]
          )
        ],
        bodyEn: [
          ...createBlocks([
            "It is highly important for civil services aspirants to distinguish between these two key terms:",
            "• One District One Product (ODOP): A socio-economic development scheme. Its primary goal is providing infrastructural support, machinery upgrades, credit subsidy, branding, and domestic/international market linkages for a selected district specialty.",
            "• Geographical Indication (GI Tag): A legal Intellectual Property Right (IPR) under the WTO framework. It is granted only when a product's unique quality, reputation, or physical traits are inherently tied to its specific geographical origin (soil, climate, or traditional skill). It offers legal protection against unauthorized commercial misuse."
          ]),
          createTable(
            "table-odop-vs-gi-en",
            "ODOP vs GI Tag Comparison",
            ["Parameter", "One District One Product (ODOP)", "Geographical Indication (GI Tag)"],
            [
              ["Basic Nature", "Economic Development and Marketing Scheme", "Legal Intellectual Property Right (IPR)"],
              ["Primary Focus", "Scaling production, credit linking, and packaging", "Safeguarding geographical origin, authenticity and quality"],
              ["Legal Status", "Government policy guidelines and budgetary support", "Statutory protection under the GI Act of 1999"],
              ["Validity Period", "As long as the scheme is active in government policy", "10 Years from registration, renewable indefinitely"]
            ]
          )
        ],
      },

      /* Section 6: ODOP in Madhya Pradesh */
      {
        _key: "sec-odop-mp",
        kind: "keyHighlights",
        title: "मध्य प्रदेश में 'एक जिला-एक उत्पाद' (ODOP) योजना",
        titleEn: "ODOP Scheme in Madhya Pradesh",
        body: [
          ...createBlocks([
            "मध्य प्रदेश में इस योजना का औपचारिक क्रियान्वयन वर्ष 2021 में शुरू किया गया था। राज्य का 'औद्योगिक नीति एवं निवेश संवर्धन विभाग' इसका नोडल विभाग है। प्रदेश के सभी 52+ जिलों के विशिष्ट उत्पादों की सूची तैयार की गई है जो परीक्षा की दृष्टि से अति महत्वपूर्ण है।",
            "• जबलपुर: मटर (जबलपुर मटर देश का प्रमुख मटर उत्पादक क्षेत्र है जो हाल ही में डॉ. रजनीकांत के प्रयासों से जीआई टैग भी प्राप्त कर चुका है)।"
          ]),
          {
            _key: "b6-img-showcase",
            _type: "image",
            asset: { _type: "reference", _ref: assetShowcase._id },
            alt: "A rustic kitchen setup showcasing MP's ODOP products: Bagh print textile, a bowl of long-grain Basmati rice, and fresh peas",
          },
          createTable(
            "table-mp-odop-hi",
            "मध्य प्रदेश के प्रमुख जिले और उनके चयनित ODOP उत्पाद",
            ["जिला (District)", "चयनित ODOP उत्पाद", "श्रेणी / प्रकृति"],
            [
              ["जबलपुर", "मटर (Jabalpur Peas)", "कृषि (सब्जी) - जीआई टैग प्राप्त"],
              ["बुरहानपुर", "केला (Burhanpur Banana)", "कृषि (फल) - जीआई टैग प्राप्त"],
              ["झाबुआ", "कड़कनाथ मुर्गा (Kadaknath Chicken)", "कृषि (मीट) - जीआई टैग प्राप्त"],
              ["रायसेन", "बासमती चावल (Basmati Rice)", "कृषि (धान)"],
              ["पन्ना", "आँवला (Amla Products)", "कृषि (फल)"],
              ["रतलाम", "रतलामी सेव (Sev Namkeen)", "खाद्य सामग्री - जीआई टैग प्राप्त"],
              ["बालाघाट", "चिन्नौर चावल (Chinnour Rice)", "कृषि (धान) - जीआई टैग प्राप्त"],
              ["धार", "बाघ प्रिंट (Bagh Print)", "हस्तशिल्प / कला - जीआई टैग प्राप्त"],
              ["भोपाल", "जरी-जरदोजी और जूट उत्पाद", "हस्तशिल्प / कपड़ा"],
              ["छतरपुर", "लकड़ी का फर्नीचर", "लघु उद्योग / शिल्प"]
            ]
          )
        ],
        bodyEn: [
          ...createBlocks([
            "In Madhya Pradesh, the formal implementation of the scheme started in 2021, driven by the Department of Industrial Policy and Investment Promotion. Distinct agricultural and handicraft products from each district have been selected to build local industrial clusters.",
            "• Jabalpur: Peas (The Patan-Jabalpur cluster is famous for sweet peas which recently secured the GI tag)."
          ]),
          {
            _key: "b6-img-showcase-en",
            _type: "image",
            asset: { _type: "reference", _ref: assetShowcase._id },
            alt: "A rustic kitchen setup showcasing MP's ODOP products: Bagh print textile, a bowl of long-grain Basmati rice, and fresh peas",
          },
          createTable(
            "table-mp-odop-en",
            "Key Madhya Pradesh Districts and Selected ODOP Items",
            ["District Name", "Selected ODOP Specialty", "Product Category"],
            [
              ["Jabalpur", "Peas (Matar)", "Agriculture - Also GI Tagged"],
              ["Burhanpur", "Banana (Kela)", "Agriculture - Also GI Tagged"],
              ["Jhabua", "Kadaknath Chicken", "Agriculture & Livestock - Also GI Tagged"],
              ["Raisen", "Basmati Rice", "Agriculture - Paddy"],
              ["Panna", "Amla (Gooseberry)", "Agriculture - Fruit Cluster"],
              ["Ratlam", "Ratlami Sev (Namkeen)", "Foodstuff - Also GI Tagged"],
              ["Balaghat", "Chinnour Rice", "Agriculture - Paddy - Also GI Tagged"],
              ["Dhar", "Bagh Print", "Handicrafts & Textiles - Also GI Tagged"],
              ["Bhopal", "Zari-Zardozi & Jute Crafts", "Textiles & Handicrafts"],
              ["Chhatarpur", "Wooden Furniture", "Small Scale Industry"]
            ]
          )
        ],
      },

      /* Section 7: Key Facts Table */
      {
        _key: "sec-quick-facts",
        kind: "factsAtAGlance",
        title: "एक जिला-एक उत्पाद (ODOP): परीक्षा स्मरणीय तथ्य",
        titleEn: "ODOP Scheme: Quick Exam Revision Pointers",
        body: [
          createTable(
            "table-odop-facts-hi",
            "ODOP परीक्षा उपयोगी तथ्य",
            ["फैक्ट पैरामीटर", "विवरण"],
            [
              ["पहल का नाम", "एक जिला-एक उत्पाद (ODOP)"],
              ["मूल अवधारणा जन्म", "जापान (वर्ष 1979 - OVOP योजना)"],
              ["भारत में पहली शुरुआत", "उत्तर प्रदेश (जनवरी 2018)"],
              ["राष्ट्रीय स्तर पर लागू", "वर्ष 2020 (PMFME योजना के तहत)"],
              ["नोडल मंत्रालय", "वाणिज्य एवं उद्योग मंत्रालय, भारत सरकार (DPIIT विभाग)"],
              ["लक्ष्य", "स्थानीय उत्पादों का विकास, ब्रांडिंग और निर्यात बढ़ाना"]
            ]
          )
        ],
        bodyEn: [
          createTable(
            "table-odop-facts-en",
            "ODOP Quick Facts",
            ["Fact Parameter", "Details"],
            [
              ["Initiative Name", "One District One Product (ODOP)"],
              ["Origin of Concept", "Japan (1979 - One Village One Product OVOP)"],
              ["First Launch in India", "Uttar Pradesh (January 2018)"],
              ["National Launch", "2020 (under PMFME scheme)"],
              ["Nodal Nodal Ministry", "Ministry of Commerce & Industry, GoI (DPIIT)"],
              ["Primary Mandate", "Local industrial cluster promotion, branding, and export growth"]
            ]
          )
        ],
      }
    ],
    mcqs: [
      {
        question: "भारत में 'एक जिला-एक उत्पाद' (ODOP) योजना की शुरुआत करने वाला पहला राज्य कौन सा था?",
        questionEn: "Which was the first Indian state to formally launch the One District One Product (ODOP) scheme?",
        options: ["मध्य प्रदेश", "गुजरात", "उत्तर प्रदेश", "महाराष्ट्र"],
        optionsEn: ["Madhya Pradesh", "Gujarat", "Uttar Pradesh", "Maharashtra"],
        correctIndex: 2,
        explanation: "उत्तर प्रदेश सरकार ने अपने स्थापना दिवस के अवसर पर जनवरी 2018 में भारत में पहली बार एक जिला-एक उत्पाद (ODOP) योजना की शुरुआत की थी।",
        explanationEn: "The Government of Uttar Pradesh formally pioneered the ODOP scheme in India, launching it in January 2018 on UP Diwas."
      },
      {
        question: "ODOP (एक जिला-एक उत्पाद) योजना की मूल अवधारणा 'वन विलेज वन प्रोडक्ट' (OVOP) किस देश से ली गई है?",
        questionEn: "The core concept of ODOP is inspired by 'One Village One Product' (OVOP) scheme of which country?",
        options: ["चीन", "जापान", "दक्षिण कोरिया", "जर्मनी"],
        optionsEn: ["China", "Japan", "South Korea", "Germany"],
        correctIndex: 1,
        explanation: "OVOP योजना की शुरुआत 1979 में जापान के ओइता प्रांत के तत्कालीन गवर्नर मोरीहिको हिरामत्सू द्वारा स्थानीय उत्पादों को बढ़ावा देने के लिए की गई थी।",
        explanationEn: "The OVOP scheme was initiated in 1979 in Oita Prefecture, Japan by Governor Morihiko Hiramatsu to promote rural self-sufficiency."
      },
      {
        question: "मध्य प्रदेश में 'एक जिला-एक उत्पाद' (ODOP) योजना के तहत जबलपुर जिले के लिए किस कृषि उत्पाद का चयन किया गया है?",
        questionEn: "Under the ODOP scheme in Madhya Pradesh, which agricultural product has been selected for Jabalpur district?",
        options: ["केला", "मटर", "आँवला", "कड़कनाथ मुर्गा"],
        optionsEn: ["Banana", "Pea (Matar)", "Amla", "Kadaknath Chicken"],
        correctIndex: 1,
        explanation: "मध्य प्रदेश में जबलपुर जिले के लिए 'मटर' (Peas) को ओडीओपी उत्पाद के रूप में चुना गया है। हाल ही में पाटन-जबलपुर के मटर को भौगोलिक संकेतक (GI Tag) भी प्राप्त हुआ है।",
        explanationEn: "Peas (Matar) have been selected as the ODOP crop for Jabalpur district in Madhya Pradesh. Recently, Patan-Jabalpur peas also secured the GI Tag."
      }
    ],
    faqs: [
      {
        question: "क्या एक उत्पाद को ओडीओपी और जीआई टैग दोनों मिल सकते हैं?",
        questionEn: "Can a single product have both ODOP status and a GI Tag?",
        answer: "हाँ, कई पारंपरिक और कृषि उत्पाद (जैसे बनारसी साड़ी, चिन्नौर चावल, जबलपुरी मटर) राज्य की ओडीओपी सूची में शामिल हैं और उन्हें कानूनी जीआई टैग भी प्राप्त है।",
        answerEn: "Yes, many traditional crafts and crops (e.g., Banarasi Saree, Chinnour Rice, Jabalpuri Peas) are both selected under the ODOP scheme and legally protected by a GI Tag."
      },
      {
        question: "राष्ट्रीय स्तर पर ODOP योजना का नोडल विभाग कौन सा है?",
        questionEn: "Which is the nodal department for the national ODOP scheme?",
        answer: "राष्ट्रीय स्तर पर इसका नेतृत्व वाणिज्य एवं उद्योग मंत्रालय का उद्योग और आंतरिक व्यापार संवर्धन विभाग (DPIIT) करता है।",
        answerEn: "At the national level, the scheme is steered by the Department for Promotion of Industry and Internal Trade (DPIIT), Ministry of Commerce and Industry."
      }
    ],
    sources: [
      {
        label: "DPIIT - Invest India ODOP Portal",
        url: "https://www.investindia.gov.in/one-district-one-product",
      },
      {
        label: "Ministry of Food Processing Industries (MoFPI) - PMFME",
        url: "https://mofpi.gov.in/pmfme",
      }
    ]
  };

  try {
    await client.createOrReplace(article);
    console.log("✨ Successfully uploaded ODOP Scheme 2026 Article to Sanity!");
  } catch (err) {
    console.error("❌ Failed to create/replace document in Sanity:", err);
  }
}

main().catch((err) => {
  console.error("❌ Error running script:", err);
  process.exit(1);
});
