import { createClient } from "@sanity/client";
import dotenv from "dotenv";
import path from "path";
import fs from "fs";

// Load env.local explicitly
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const {
  NEXT_PUBLIC_SANITY_PROJECT_ID: projectId,
  NEXT_PUBLIC_SANITY_DATASET: dataset,
  SANITY_API_WRITE_TOKEN: token,
} = process.env;

if (!projectId || !dataset || !token) {
  console.error("❌ Missing Sanity variables in .env.local!");
  process.exit(1);
}

const client = createClient({
  projectId,
  dataset,
  token,
  apiVersion: "2024-10-01",
  useCdn: false,
});

// Helper to convert an array of strings into separate Portable Text blocks
function createBlocks(items: string[]): any[] {
  return items.map((text, idx) => {
    const randomSuffix = Math.random().toString(36).substring(2, 9);
    return {
      _key: `block-${idx}-${randomSuffix}`,
      _type: "block",
      style: "normal",
      children: [
        {
          _key: `span-${idx}-${randomSuffix}`,
          _type: "span",
          text: text,
        },
      ],
    };
  });
}

// Helper to create a custom block with a link
function createLinkBlock(textBefore: string, linkText: string, textAfter: string, url: string): any {
  const randomSuffix = Math.random().toString(36).substring(2, 9);
  return {
    _key: `block-link-${randomSuffix}`,
    _type: "block",
    style: "normal",
    children: [
      {
        _key: `span-before-${randomSuffix}`,
        _type: "span",
        text: textBefore,
      },
      {
        _key: `span-link-${randomSuffix}`,
        _type: "span",
        text: `[${linkText}](${url})`,
      },
      {
        _key: `span-after-${randomSuffix}`,
        _type: "span",
        text: textAfter,
      }
    ]
  };
}

// Helper to create a custom table block
function createTable(key: string, caption: string, headers: string[], rows: string[][]): any {
  return {
    _key: key,
    _type: "table",
    table: {
      caption,
      headers,
      rows,
    },
  };
}

async function main() {
  console.log("🚀 Starting upload process for Jabalpur Matar & Singhada GI Tags 2026 Current Affairs Article...");

  // Image files generated by the generate_image tool
  const imagePaths = {
    banner: path.resolve(process.cwd(), "/Users/aakariastech/.gemini/antigravity-ide/brain/f3368bc5-9762-4cc4-a6af-e2c9e58d3968/jabalpur_gi_tag_celebration_1784200559515.png"),
    matar: path.resolve(process.cwd(), "/Users/aakariastech/.gemini/antigravity-ide/brain/f3368bc5-9762-4cc4-a6af-e2c9e58d3968/jabalpuri_matar_field_1784200533904.png"),
    singhada: path.resolve(process.cwd(), "/Users/aakariastech/.gemini/antigravity-ide/brain/f3368bc5-9762-4cc4-a6af-e2c9e58d3968/jabalpur_singhada_harvest_1784200547839.png"),
  };

  // Check if files exist
  if (!fs.existsSync(imagePaths.banner) || !fs.existsSync(imagePaths.matar) || !fs.existsSync(imagePaths.singhada)) {
    console.error("❌ Required images not found in the generated paths!");
    process.exit(1);
  }

  // 1. Upload Banner Image
  console.log("📸 Uploading banner image...");
  const assetBanner = await client.assets.upload("image", fs.createReadStream(imagePaths.banner), {
    filename: "jabalpur_gi_tag_celebration.png",
  });
  console.log(`✔ Uploaded banner image. Asset ID: ${assetBanner._id}`);

  // 2. Upload Matar Image
  console.log("📸 Uploading matar image...");
  const assetMatar = await client.assets.upload("image", fs.createReadStream(imagePaths.matar), {
    filename: "jabalpuri_matar_field.png",
  });
  console.log(`✔ Uploaded matar image. Asset ID: ${assetMatar._id}`);

  // 3. Upload Singhada Image
  console.log("📸 Uploading singhada image...");
  const assetSinghada = await client.assets.upload("image", fs.createReadStream(imagePaths.singhada), {
    filename: "jabalpur_singhada_harvest.png",
  });
  console.log(`✔ Uploaded singhada image. Asset ID: ${assetSinghada._id}`);

  // 4. Construct the Article document with _type: "currentAffairs"
  const article = {
    _id: "ca-jabalpur-matar-singhada-gi-tag-2026",
    _type: "currentAffairs",
    slug: { _type: "slug", current: "jabalpur-matar-singhada-gi-tag-2026" },
    title: "जबलपुर के मटर और सिंघाड़ा को मिला GI टैग: नर्मदा घाटी की कृषि विरासत को मिली राष्ट्रीय पहचान",
    titleEn: "Jabalpur Peas and Water Chestnut Secure GI Tags: National Recognition for Narmada Valley's Agricultural Heritage",
    excerpt: "मध्य प्रदेश के जबलपुर के दो प्रसिद्ध कृषि उत्पादों—जबलपुरी मटर (Jabalpuri Matar) और जबलपुर सिंघाड़ा (Jabalpur Singhada) को भारत सरकार द्वारा भौगोलिक संकेतक (Geographical Indication - GI) टैग प्रदान किया गया है। यह देश में पहली बार है जब मटर और सिंघाड़े को जीआई मान्यता मिली है।",
    excerptEn: "Two famous agricultural products of Jabalpur, Madhya Pradesh—Jabalpuri Matar (Peas) and Jabalpur Singhada (Water Chestnut)—have been granted GI tags by the Government of India, establishing a historic milestone.",
    ca_date: "2026-07-16",
    publishedAt: new Date().toISOString(),
    featured: true,
    readingTime: 6,
    keywords: [
      "Jabalpur Peas GI Tag",
      "Jabalpur Singhada GI Tag",
      "Jabalpuri Matar",
      "Jabalpur Water Chestnut",
      "MP Current Affairs 2026",
      "MPPSC GK Current Affairs",
      "UPSC GI Tags list",
      "Geographical Indication Act India",
      "ODOP Jabalpur Peas",
      "जबलपुर मटर जीआई टैग",
      "जबलपुर सिंघाड़ा जीआई टैग",
      "मध्य प्रदेश करेंट अफेयर्स",
      "एमपीपीएससी प्रारंभिक परीक्षा",
      "जीआई रजिस्ट्री चेन्नई"
    ],
    category: { _type: "reference", _ref: "cat-mpgk" }, // MP GK subject category
    author: { _type: "reference", _ref: "author-aakar" },
    tags: [
      { _type: "reference", _ref: "tag-upsc" },
      { _type: "reference", _ref: "tag-mppsc" },
      { _type: "reference", _ref: "tag-prelims" },
      { _type: "reference", _ref: "tag-mains" },
      { _type: "reference", _ref: "tag-mp-ca" }, // MP Current Affairs
    ],
    syllabus: ["GS-3", "Prelims-GS"],
    featuredImage: {
      _type: "image",
      asset: { _type: "reference", _ref: assetBanner._id },
      alt: "A professional celebration banner for Jabalpur's GI Tag showing green peas on the left and fresh water chestnuts on the right",
    },
    sections: [
      /* Section 1: Context */
      {
        _key: "sec-context",
        kind: "whyInNews",
        title: "प्रसंग (Context)",
        titleEn: "Why in News?",
        body: createBlocks([
          "मध्य प्रदेश के जबलपुर के दो प्रसिद्ध कृषि उत्पादों—जबलपुरी मटर (Jabalpuri Matar) और जबलपुर सिंघाड़ा (Jabalpur Singhada)—को भारत सरकार द्वारा भौगोलिक संकेतक (Geographical Indication – GI) टैग प्रदान किया गया है। चेन्नई स्थित जीआई रजिस्ट्री ने 26 जून 2026 को आधिकारिक तौर पर इन उत्पादों को जीआई जर्नल में पंजीकृत किया। देश में यह पहला अवसर है जब किसी क्षेत्र के मटर और सिंघाड़े को एक साथ जीआई टैग प्राप्त हुआ है, जिससे नर्मदा घाटी की कृषि विरासत को एक राष्ट्रीय और अंतरराष्ट्रीय पहचान मिली है।"
        ]),
        bodyEn: createBlocks([
          "Two popular agricultural specialties of Jabalpur, Madhya Pradesh—Jabalpuri Matar (Peas) and Jabalpur Singhada (Water Chestnut)—have been officially awarded the Geographical Indication (GI) tags by the Government of India. The GI Registry in Chennai registered both products in the GI Journal on June 26, 2026. This is the first time in India that peas and water chestnuts from any region have secured GI recognition, putting Narmada Valley's agricultural heritage on the global map."
        ]),
      },

      /* Section 2: Detailed features of Jabalpur Peas and Singhada */
      {
        _key: "sec-products-features",
        kind: "keyHighlights",
        title: "जबलपुरी मटर और सिंघाड़ा की विशिष्ट विशेषताएं",
        titleEn: "Key Highlights & Distinct Features",
        body: [
          ...createBlocks([
            "जबलपुर के इन दोनों उत्पादों में अद्वितीय गुण और स्थानीय भौगोलिकता का प्रभाव पाया जाता है:",
            "• जबलपुरी मटर (Jabalpuri Matar): नर्मदा घाटी की उपजाऊ और आर्द्र मिट्टी में उत्पादित होने के कारण इस मटर का स्वाद असाधारण रूप से मीठा होता है। यह अधिक पौष्टिक होता है और अपनी विशिष्ट गुणवत्ता के कारण काफी प्रसिद्ध है। जबलपुर का पाटन क्षेत्र मटर उत्पादन का प्रमुख केंद्र है। जबलपुर मटर केंद्र सरकार की 'एक जिला-एक उत्पाद' (ODOP) योजना का भी हिस्सा है।"
          ]),
          {
            _key: "b2-img-matar",
            _type: "image",
            asset: { _type: "reference", _ref: assetMatar._id },
            alt: "Fresh green Jabalpuri Matar inside pods displayed in a rustic wooden basket on a local farm in Narmada Valley",
          },
          ...createBlocks([
            "• जबलपुर सिंघाड़ा (Jabalpur Singhada): जबलपुर के स्वच्छ, प्राकृतिक जलाशयों और तालाबों में इसका पारंपरिक रूप से उत्पादन किया जाता है। इसका बेहतरीन स्वाद, बड़ा आकार और उच्च पोषण स्तर इसे देश भर के बाजारों में अत्यधिक लोकप्रिय बनाते हैं।"
          ]),
          createLinkBlock(
            "• आवेदन प्रक्रिया (Application Journey): इन उत्पादों को जीआई टैग दिलाने में 'मैकलसुता फार्मर प्रोड्यूसर कंपनी' (FPO), पाटन की मुख्य भूमिका रही। इन्होंने मटर के लिए अक्टूबर 2023 और सिंघाड़े के लिए जनवरी 2024 में आवेदन किया था। इस प्रक्रिया में मध्य प्रदेश उद्यानिकी विभाग और जीआई विशेषज्ञ ",
            "'जीआई मैन ऑफ इंडिया' पद्मश्री डॉ. रजनीकांत",
            " का विशेष योगदान रहा।",
            "/current-affairs/dr-rajnikant-gi-man-of-india"
          ),
          {
            _key: "b2-img-singhada",
            _type: "image",
            asset: { _type: "reference", _ref: assetSinghada._id },
            alt: "Glossy dark brown and green Jabalpur Singhada water chestnuts freshly harvested and resting in pond water",
          }
        ],
        bodyEn: [
          ...createBlocks([
            "Both agricultural products possess distinct qualities influenced by the unique soil and environmental conditions of the Narmada Valley region:",
            "• Jabalpuri Matar (Peas): Cultivated in the highly fertile and moist soils of the Narmada Valley, these peas are known for their exceptionally sweet taste, vibrant green color, and high nutrient profile. The Patan area of Jabalpur is a major cultivation hub. The crop is also selected under the central government's One District One Product (OPOD) initiative."
          ]),
          {
            _key: "b2-img-matar-en",
            _type: "image",
            asset: { _type: "reference", _ref: assetMatar._id },
            alt: "Fresh green Jabalpuri Matar inside pods displayed in a rustic wooden basket on a local farm in Narmada Valley",
          },
          ...createBlocks([
            "• Jabalpur Singhada (Water Chestnut): Cultivated traditionally in the clean and freshwater ponds of Jabalpur district, these water chestnuts are distinguished by their large size, crunchy texture, excellent taste, and rich mineral content."
          ]),
          createLinkBlock(
            "• Application Journey: The 'Maikalsuta Farmer Producer Organization' (FPO) located in Patan initiated the application process in October 2023 (for peas) and January 2024 (for water chestnuts). The state horticulture department and renowned GI specialist ",
            "Padmashree Dr. Rajnikant (often called the 'GI Man of India')",
            " played crucial roles in securing this status.",
            "/current-affairs/dr-rajnikant-gi-man-of-india"
          ),
          {
            _key: "b2-img-singhada-en",
            _type: "image",
            asset: { _type: "reference", _ref: assetSinghada._id },
            alt: "Glossy dark brown and green Jabalpur Singhada water chestnuts freshly harvested and resting in pond water",
          }
        ],
      },

      /* Section 3: What is GI Tag background */
      {
        _key: "sec-what-is-gi",
        kind: "background",
        title: "भौगोलिक संकेतक (GI Tag) के बारे में बुनियादी तथ्य",
        titleEn: "Understanding Geographical Indications (GI Tags)",
        body: createBlocks([
          "• परिचय: भौगोलिक संकेतक (GI) एक ऐसा नाम या चिह्न है जिसका उपयोग उन उत्पादों पर किया जाता है जिनकी एक विशिष्ट भौगोलिक उत्पत्ति होती है और जिनमें उस उत्पत्ति के कारण गुण या प्रतिष्ठा होती है।",
          "• अधिनियम: भारत में जीआई पंजीकरण 'माल का भौगोलिक उपदर्शन (पंजीकरण और संरक्षण) अधिनियम, 1999' के तहत विनियमित होता है, जो 15 सितंबर 2003 से लागू हुआ।",
          "• प्राधिकरण: इसका पंजीकरण भौगोलिक संकेतक रजिस्ट्री, चेन्नई द्वारा किया जाता है। यह वाणिज्य और उद्योग मंत्रालय के उद्योग और आंतरिक व्यापार संवर्धन विभाग (DPIIT) के अधीन काम करता है।",
          "• वैधता: जीआई टैग पंजीकरण 10 वर्षों के लिए वैध होता है, जिसे बाद में नवीनीकृत किया जा सकता है।"
        ]),
        bodyEn: createBlocks([
          "• Introduction: A Geographical Indication (GI) is a sign used on products that have a specific geographical origin and possess qualities, reputation or characteristics that are essentially attributable to that place of origin.",
          "• Legislation: Governed in India under the Geographical Indications of Goods (Registration and Protection) Act, 1999, which came into force on September 15, 2003.",
          "• Authority: Administered by the GI Registry in Chennai, functioning under the DPIIT, Ministry of Commerce and Industry, Government of India.",
          "• Validity: A GI tag is granted for a period of 10 years, which can be renewed indefinitely upon expiry."
        ]),
      },

      /* Section 4: Benefits to Farmers */
      {
        _key: "sec-farmers-benefits",
        kind: "importance",
        title: "जीआई टैग से किसानों को मिलने वाले लाभ",
        titleEn: "Benefits of the GI Tag for Farmers",
        body: createBlocks([
          "• कानूनी संरक्षण: नकली और मिलावटी उत्पादों की बिक्री पर रोक लगती है। केवल जबलपुर नर्मदा क्षेत्र के किसान ही इन विशिष्ट नामों का उपयोग कर सकेंगे।",
          "• आर्थिक लाभ: राष्ट्रीय और अंतरराष्ट्रीय स्तर पर ब्रांड वैल्यू बढ़ने से उत्पादों को अधिक मूल्य प्राप्त होगा, जिससे किसानों की आय में सुधार होगा।",
          "• निर्यात में वृद्धि: जैविक कृषि को बढ़ावा मिलेगा, जिससे यूरोपीय और मध्य-पूर्वी देशों में निर्यात की संभावनाएं बढ़ेंगी।",
          "• स्थानीय रोजगार: स्थानीय खाद्य प्रसंस्करण उद्योगों (Food Processing Units) का विकास होगा जिससे ग्रामीण युवाओं को रोजगार मिलेगा।"
        ]),
        bodyEn: createBlocks([
          "• Legal Protection: Prevents unauthorized branding or imitation. Only registered farmers in the Narmada Valley of Jabalpur can market their produce under these names.",
          "• Higher Income: Enhanced global branding and direct market access allow farmers to demand premium pricing, elevating rural prosperity.",
          "• Boost in Exports: Drives standardisation and organic farming certification, paving the way for exporting these items to global markets.",
          "• Local Employment: Encourages the setup of local sorting, packaging, and food-processing units, generating rural employment."
        ]),
      },

      /* Section 5: MP GI Tags list table */
      {
        _key: "sec-mp-gi-list",
        kind: "factsAtAGlance",
        title: "मध्य प्रदेश के प्रमुख भौगोलिक संकेतक (GI Tags)",
        titleEn: "Important GI Tags of Madhya Pradesh",
        body: [
          ...createBlocks([
            "एमपीपीएससी (MPPSC) एवं अन्य राज्य परीक्षाओं के लिए अत्यंत महत्वपूर्ण सूची:"
          ]),
          createTable(
            "table-mp-gi-tags-hi",
            "मध्य प्रदेश के प्रमुख जीआई उत्पाद",
            ["उत्पाद (GI Product)", "प्रकार", "संबंधित क्षेत्र/जिला"],
            [
              ["चंदेरी साड़ी", "हथकरघा / कपड़ा", "अशोकनगर"],
              ["महेश्वरी साड़ी", "हथकरघा / कपड़ा", "खरगोन"],
              ["बाघ प्रिंट", "हस्तशिल्प / प्रिंट", "धार"],
              ["रतलामी सेव", "खाद्य सामग्री", "रतलाम"],
              ["कड़कनाथ मुर्गा", "कृषि / मीट", "झाबुआ"],
              ["चिन्नौर चावल", "कृषि / धान", "बालाघाट"],
              ["सुंदरजा आम", "कृषि / फल", "रीवा"],
              ["जबलपुरी मटर", "कृषि / सब्जी", "जबलपुर (नवीनतम 2026)"],
              ["जबलपुर सिंघाड़ा", "कृषि / फल", "जबलपुर (नवीनतम 2026)"]
            ]
          )
        ],
        bodyEn: [
          ...createBlocks([
            "Quick revision index for civil service aspirants:"
          ]),
          createTable(
            "table-mp-gi-tags-en",
            "Key GI tags of Madhya Pradesh",
            ["Product Name", "Category", "Origin District"],
            [
              ["Chanderi Saree", "Handloom & Textiles", "Ashoknagar"],
              ["Maheshwari Saree", "Handloom & Textiles", "Khargone"],
              ["Bagh Print", "Handicrafts & Art", "Dhar"],
              ["Ratlami Sev", "Foodstuff", "Ratlam"],
              ["Kadaknath Chicken", "Agriculture & Meat", "Jhabua"],
              ["Chinnour Rice", "Agriculture & Paddy", "Balaghat"],
              ["Sundarja Mango", "Agriculture & Fruit", "Rewa"],
              ["Jabalpuri Matar", "Agriculture & Pea", "Jabalpur (New 2026)"],
              ["Jabalpur Singhada", "Agriculture & Fruit", "Jabalpur (New 2026)"]
            ]
          )
        ],
      }
    ],
    mcqs: [
      {
        question: "भौगोलिक संकेतक (GI) टैग प्राप्त करने वाले 'जबलपुरी मटर' और 'जबलपुर सिंघाड़ा' किस राज्य से संबंधित हैं?",
        questionEn: "Jabalpuri Matar and Jabalpur Singhada, which recently received GI tags, belong to which Indian state?",
        options: ["उत्तर प्रदेश", "छत्तीसगढ़", "राजस्थान", "मध्य प्रदेश"],
        optionsEn: ["Uttar Pradesh", "Chhattisgarh", "Rajasthan", "Madhya Pradesh"],
        correctIndex: 3,
        explanation: "मध्य प्रदेश के जबलपुर जिले के इन दोनों प्रसिद्ध कृषि उत्पादों को हाल ही में जून 2026 में भारत सरकार द्वारा प्रतिष्ठित जीआई टैग प्रदान किया गया है।",
        explanationEn: "Both popular agricultural products from Jabalpur, Madhya Pradesh were awarded the prestigious GI status by the Government of India in June 2026."
      },
      {
        question: "भारत में भौगोलिक संकेतक रजिस्ट्री (GI Registry) कहाँ स्थित है?",
        questionEn: "Where is the Geographical Indications Registry (GI Registry) located in India?",
        options: ["नई दिल्ली", "मुंबई", "चेन्नई", "बेंगलुरु"],
        optionsEn: ["New Delhi", "Mumbai", "Chennai", "Bengaluru"],
        correctIndex: 2,
        explanation: "भारत में जीआई टैग का पंजीकरण और नियमन चेन्नई स्थित भौगोलिक संकेतक रजिस्ट्री (GI Registry) द्वारा किया जाता है।",
        explanationEn: "The GI registration and regulation in India are managed by the GI Registry located in Chennai, Tamil Nadu."
      },
      {
        question: "जीआई (Geographical Indication) टैग की सामान्य वैधता अवधि कितने वर्षों की होती है?",
        questionEn: "What is the standard validity period of a Geographical Indication (GI) tag in India?",
        options: ["5 वर्ष", "10 वर्ष", "15 वर्ष", "20 वर्ष"],
        optionsEn: ["5 Years", "10 Years", "15 Years", "20 Years"],
        correctIndex: 1,
        explanation: "जीआई पंजीकरण 10 वर्षों के लिए वैध होता है, जिसके बाद इसे दोबारा शुल्क देकर नवीनीकृत किया जा सकता है।",
        explanationEn: "A GI tag is valid for a period of 10 years, which can be subsequently renewed upon paying the required fee."
      }
    ],
    faqs: [
      {
        question: "जबलपुरी मटर और सिंघाड़े को जीआई टैग किस तारीख को मिला?",
        questionEn: "On which date were Jabalpuri Matar and Singhada registered as GI?",
        answer: "चेन्नई स्थित भौगोलिक संकेतक रजिस्ट्री ने दोनों उत्पादों को 26 जून 2026 को जीआई जर्नल में पंजीकृत किया।",
        answerEn: "The GI Registry based in Chennai registered both products in the official GI Journal on June 26, 2026."
      },
      {
        question: "क्या जबलपुर मटर किसी अन्य सरकारी योजना में शामिल है?",
        questionEn: "Is Jabalpuri Matar part of any other government scheme?",
        answer: "हाँ, जबलपुरी मटर केंद्र सरकार की 'एक जिला-एक उत्पाद' (ODOP) योजना के अंतर्गत जबलपुर जिले के लिए चयनित उत्पाद है।",
        answerEn: "Yes, Jabalpuri Matar is selected for Jabalpur district under the central government's One District One Product (ODOP) scheme."
      }
    ],
    sources: [
      {
        label: "Press Information Bureau (PIB)",
        url: "https://pib.gov.in/PressReleasePage.aspx?PRID=20260716",
      },
      {
        label: "Geographical Indications Registry, Chennai",
        url: "https://ipindia.gov.in/newsdetail.htm?2026-gi",
      }
    ]
  };

  try {
    await client.createOrReplace(article);
    console.log("✨ Successfully uploaded Jabalpur Peas & Singhada GI Tag Article to Sanity!");
  } catch (err) {
    console.error("❌ Failed to create/replace document in Sanity:", err);
  }
}

main().catch((err) => {
  console.error("❌ Error running script:", err);
  process.exit(1);
});
